### ISSUE TITLE
How to create a new map?

### ISSUE THREAD

**Issue by YoungCapta1n** [LaiYanKai/2D#1]
Hi,

I notice that both the map (*.map) and a scene (*.map.scen) are used in the path planning module. How to create a new map? And how to ignore the scene in the cpp code? Thanks for your time!

**Comment by LaiYanKai** [comment]
Sorry for the late response. Didn't expect an issue to be raised so fast.
The grid can be provided in bool* array form, stated in the Readme (see https://github.com/LaiYanKai/2D/blob/main/P2D/include/P2D/grid.hpp#L47)
For example,
```cpp
P2D::V2 size_cell(X, Y); // X is number of rows, Y is number of columns. This coordinate frame may be different from the ones used in other systems, like ROS nav2.
bool* bool_ptr = {new bool[size_cell.x * size_cell.y]};
// fill the bool_ptr with bool_ptr[i] (see image below) true for occupied, false for free.
P2D::Grid grid(bool_ptr, size_cell);
P2D::R2::R2 r2(&grid); // init R2
P2D::V2 start_coord(x1, y1);
P2D::V2 goal_coord(x2, y2);
r2.run(start_coord, goal_coord); // find path.
delete[] bool_ptr; // release mem.
```
The grid constructor is currently untested. Let me know if you see errors from the function.
![image](https://github.com/LaiYanKai/2D/assets/28682226/454d6426-138e-45d2-91e4-75621e8aa35a)

**Comment by YoungCapta1n** [comment]
Thanks for your time!
